// AUTHENTICATION
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// CREATE COURSES || TEACHERS SECTION
export const CREATE_NEW_COURSE = "CREATE_NEW_COURSE";
export const CREATE_COURSE_FAIL = "CREATE_COURSE_FAIL";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const DELETE_COURSE = "DELETE_COURSE";

// CART
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_TO_CART = "REMOVE_TO_CART";